title: DEBORAH ZICHAT TURANK
logo: https://github.com/debbhie/debby/commit/8745492840597c9c96ee65dac10c37c12ffe9f55#commitcomment-139307939
description: text below image
show_downloads: true
theme: jekyll-theme-minimal
